CFLAGS =  -O -g


#LIBS
LIBS := `pkg-config --cflags --libs gstreamer-1.0 gstreamer-pbutils-1.0`


#########################################################################
playback_player1:playback-tutorial-1.o
	gcc  $(CFLAGS)  -o playback_player1  playback-tutorial-1.o  $(LIBS)

#playback-tutorial-1.o
playback-tutorial-1.o:playback-tutorial-1.c
	gcc  -c -g playback-tutorial-1.c $(LIBS)

#########################################################################



# #########################################################################
# playback_player_Extend:playback-tutorial-1_Extend.o
# 	gcc  $(CFLAGS)  -o playback_player_Extend  playback-tutorial-1.o  $(LIBS)

# #playback-tutorial-1.o
# playback-tutorial-1_Extend.o:playback-tutorial-1_Extend.c
# 	gcc  -c -g playback-tutorial-1_Extend.c $(LIBS)

# #########################################################################


# #########################################################################
# playback_player1:playback-tutorial-1.o
# 	gcc  $(CFLAGS)  -o playback_player1  playback-tutorial-1.o  $(LIBS)

# #playback-tutorial-1.o
# playback-tutorial-1.o:playback-tutorial-1.c
# 	gcc  -c -g playback-tutorial-1.c $(LIBS)

# #########################################################################


# #########################################################################
# playback_player1:playback-tutorial-1.o
# 	gcc  $(CFLAGS)  -o playback_player1  playback-tutorial-1.o  $(LIBS)

# #playback-tutorial-1.o
# playback-tutorial-1.o:playback-tutorial-1.c
# 	gcc  -c -g playback-tutorial-1.c $(LIBS)

# #########################################################################


# #########################################################################
# playback_player1:playback-tutorial-1.o
# 	gcc  $(CFLAGS)  -o playback_player1  playback-tutorial-1.o  $(LIBS)

# #playback-tutorial-1.o
# playback-tutorial-1.o:playback-tutorial-1.c
# 	gcc  -c -g playback-tutorial-1.c $(LIBS)

# #########################################################################


# # .PHONY: clean  
# # clean:  
# # 	rm -rf *.o  playback_player*